### ISSUE TITLE
Support for NuxtJs (SSR)

### ISSUE THREAD

**Issue by ervansanjaya** [userback/widget-js#29]
Hi Userback team, 

I want to ask if it is possible to integrate with NuxtJs (v2.12.2)?

I have tried to install the Vue version but got this error
![image](https://user-images.githubusercontent.com/14139756/190188583-2a35e170-f8d6-4e18-bcac-f7222d36857b.png)

Here's how I implement it
/plugins/userback.js
![image](https://user-images.githubusercontent.com/14139756/190188744-255540da-332c-44d9-bf0f-b98f9391b506.png)

/nuxt.config.js
![image](https://user-images.githubusercontent.com/14139756/190188883-e9147836-d7a4-41d5-8e7b-f418bfee9e10.png)

Appreciate any help, thanks!

**Comment by ervansanjaya** [comment]
Hi @Shard & @lee-userback perharps you guys got some light on this?

Thanks!

**Comment by Shard** [comment]
Hi @ervansanjaya,

Thanks for bringing this to our attention.

As you mentioned in the title, I think this is an issue with SSR/SSG as we haven't had the chance to create a nuxtjs example and test that functionality yet.

I will put aside some time this week to investigate a bit more and hopefully the fixes are simple enough we can release a new version soon as we do see this as an important use case.

**Comment by ervansanjaya** [comment]
Thanks for the concern @Shard, I hope we can sort this out soon!

**Comment by ervansanjaya** [comment]
Hi good day @Shard, just wanted to follow up if you have got a chance to check on this?

Thanks!

**Comment by agueric** [comment]
Hi! Any update on this? Facing similar issue. @Shard

**Comment by meirroth** [comment]
I'm interested in NuxtJs support too.

**Comment by ervansanjaya** [comment]
Hi @Shard, is there any update from this enhancement request please?
Thanks

**Comment by Shard** [comment]
Hi @ervansanjaya 

There has been a bit of work committed to develop to add support for nuxt3.

We made an initial attempt to add vue2 and nuxt2 but ran into a few roadblocks with how we initially built the plugin that makes simply attaching the the "global `Vue` prototype" non trivial.

I am currently working on PR #36  to add `vue-demi` and change the plugin to use the composition api. When that is done, we will be able to finalize and cut a new `0.2.0` release.

**Comment by ervansanjaya** [comment]
Glad to hear the updates @Shard

Thank you! I hope we can sort this vue 2 thing as soon as possible

**Comment by Shard** [comment]
Hey guys,

Support for vue2 has been released in v0.2.0 (#44) under the new package `@userback/vue2` 🎉 

This also includes examples for both [nuxt2](https://github.com/userback/widget-js/tree/v0.2.0/examples/nuxt2) and [nuxt3](https://github.com/userback/widget-js/tree/v0.2.0/examples/nuxt) which demonstate how to setup a client side plugin.

If you run into any issues or notice any functionality missing feel free to open another PR.

Cheers.
