### ISSUE TITLE
Accessing `userback` inside the setup

### ISSUE THREAD

**Issue by zaherg** [userback/widget-js#30]
What is the best way to access `userback` from within `setup`?
My case is simple, I want to use the API to set the email and the name of the user automatically.

My stack is Laravel & [Inertiajs](inertiajs.com], and what I am trying to do is to get the props that I set for Inertia via Laravel and use it to set the email and name of the user, so they don't have to do it manually.

and since `$userback` is a `globalProperties` https://github.com/userback/widget-js/blob/9bece3af53737825b77c710d23def4857dc28c63/widget-vue/vue.tsx#L13-L16 I can't find a simple way to access it and modify the data.

Also, I can use it to hide the widget on specific pages without the need to do anything on userback management portal, a simple `userback.hide()` would work like

```javascript
<scrip setup>
import {userback} from '@userback/widget/vue';

// This way I can hide the widget without the need to specify the URL
// in the configuration page
userback.hide();

// or

userback.email = 'myemail@gmailmail.com';

</script>
```

PS: I am on a company plan, so yes I can access the JS api.

Thanks

**Comment by lee-userback** [comment]
See the code below:
```
import Userback from "@userback/widget";
Userback(widget_token).then((ub) => {
    ub.hide(); // access ub (userback) here. 
});
```

**Comment by lee-userback** [comment]
See the code below:

```
import Userback from "@userback/widget";

Userback(widget_token).then((ub) => {
    ub.hide(); // access ub (userback) here. 
});
```

**Comment by zaherg** [comment]
So what is the value of using a `Vuejs` plugin if I need to pass the token around and import the widget directly in my `Vuejs` code to access those simple functions inside the `setup`?

@lee-userback Correct me if I am wrong or misunderstood your code, but the only way to do that is to just not use the `Vuejs` plugin? and import the widget directly in my code right?
