### ISSUE TITLE
require() of ES Module

### ISSUE THREAD

**Issue by ekwoka** [userback/widget-js#45]
This is in a next app, and it's quite confusing.

It seems like, for some reason, it's going to `@userback/react` but grabbing the `cjs` instead of the `mjs` file but then trying to grab the `widget.mjs`

I can only guess there is some kind of conflict with the exports

**Comment by Shard** [comment]
Thanks for your PR @ekwoka, I have merged the PR and cut a new release of  `v0.2.1`.

Hopefully that resolves the last of our importing issues 🎉
