### ISSUE TITLE
npm install error v0.3.3

### ISSUE THREAD

**Issue by Ares328** [userback/widget-js#69]
There seems to be an issue with the newest version 0.3.3, I'm getting this error: [npm ERR! Unsupported URL Type "workspace:": workspace:*]

I rolled back to version 0.3.2, but it still didn't work and we had to add an override:
`
"overrides": {
    "
@Userback/react": {
      "
@Userback/widget": "0.3.2"
    }
  }
`

**Comment by Ares328** [comment]
send help :)

**Comment by Repomn** [comment]
same

**Comment by hunterdes** [comment]
This should be fixed in 0.3.4.
