### ISSUE TITLE
 window.Userback.init is not a function

### ISSUE THREAD

**Issue by win-ly** [userback/widget-js#72]
Suddenly I found that the project's Userback didn't work and threw an error. I checked my code and didn't make any changes recently. So I checked the official documentation again and used the official examples to test and found that the same error was thrown.
<img width="1460" alt="image" src="https://github.com/user-attachments/assets/00c6279d-228c-43c1-b2de-6d89f3cb4092">

After investigation, we found that the init method should be executed before the userback script is loaded. So how can we avoid this?

**Comment by skyflyer** [comment]
I just want to add this happens with plain old HTML/JS as well. The window.Userback object is not initialized when script element's `onload` handler is fired.

**Comment by lee-userback** [comment]
This is due to the whole widget code was made async. It should be fixed now.
