### ISSUE TITLE
Widget doen't works on firefox

### ISSUE THREAD

**Issue by daboudii** [userback/widget-js#75]
Hi, 

Just setup the widget with npm, it is working on Chrome but not firefox. 

Here is the error in console : 

![Screenshot from 2024-11-04 10-55-14](https://github.com/user-attachments/assets/e6a89652-bd3b-4ffa-9efb-e8c1f1d84cf3)

**Comment by hunterdes** [comment]
Hi there

Could you please share which version of Firefox you’re using, along with your operating system (e.g., Windows 10, macOS Monterey)? This will help us better assist you!

**Comment by daboudii** [comment]
Hi,

```
Version 131.0.3 (64-bit)
Mozilla Firefox Snap for Ubuntu
canonical-002 - 1.0
```
 It is also not working on 
 
 ```
 Version 132.0
Android 13
 ```

**Comment by hunterdes** [comment]
Hi

We've managed to replicate a similar error after testing with some Firefox extensions. Could I ask you to double-check if you have any extensions enabled in Firefox? This could help us confirm if they're contributing to the issue.

Thanks very much for you cooperation!

**Comment by daboudii** [comment]
Hi, 

Yes my bad it is related to uBlock Origin for my Ubuntu version and No script for the Android (Harder to remember since there is no console there)
