### ISSUE TITLE
Adding custom data is not taken into feedback

### ISSUE THREAD

**Issue by daboudii** [userback/widget-js#76]
Hi,

I just try to add simple custom data but they do not appear in the feedback

```ts
Userback(**//My project token//** );

getUserback().custom_data({
    app_version: packageJson.version,
    instance: 'alpha',
});
```

**Comment by hunterdes** [comment]
Hi there

`setData` is the function to set the custom data.

Here is link: https://docs.userback.io/docs/javascript-sdk#custom-data

For your code example, it should be like
```
Userback(**//My project token//** );

getUserback().setData({
    app_version: packageJson.version,
    instance: 'alpha',
});
```

**Comment by daboudii** [comment]
Thank you for your answer, I also realize that my company have just Startup plan so it won't work.
